import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000'
const labels={HIGH:'high',MEDIUM:'medium',LOW:'low',OPEN:'open',UNDER_REVIEW:'review',CORRECTED:'corrected',REJECTED:'rejected'}
function App(){
 const [token,setToken]=useState(localStorage.getItem('token')||''); const [user,setUser]=useState(JSON.parse(localStorage.getItem('user')||'null')); const [view,setView]=useState('dashboard'); const [message,setMessage]=useState(''); const [data,setData]=useState({})
 const api=async(path,options={})=>{const res=await fetch(`${API}/api${path}`,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})}});const payload=await (res.headers.get('content-type')?.includes('json')?res.json():res.text());if(!res.ok)throw new Error(typeof payload==='string'?payload:(payload.detail||'Request failed'));return payload}
 const load=async(name,path)=>{try{setData(d=>({...d,[name]:await api(path)}))}catch(e){setMessage(e.message)}}
 useEffect(()=>{if(token) load('summary','/summary')},[token])
 const logout=()=>{localStorage.clear();setToken('');setUser(null);setData({});setView('dashboard')}
 if(!token||!user)return <Login onLogin={(x)=>{localStorage.setItem('token',x.access_token);localStorage.setItem('user',JSON.stringify(x.user));setToken(x.access_token);setUser(x.user)}} api={api}/>
 const nav=['dashboard','upload','exceptions','verified','audit'];return <div className="app"><aside><div className="brand">INTAIN <span>VERIFY</span></div><p className="role">{user.role.replace('_',' ')}</p>{nav.map(x=><button key={x} className={view===x?'nav active':'nav'} onClick={()=>setView(x)}>{x}</button>)}<button className="nav" onClick={()=>window.open(`${API}/docs`,'_blank')}>API Docs</button><button className="logout" onClick={logout}>Sign out</button></aside><main><header><div><h1>{view[0].toUpperCase()+view.slice(1)}</h1><p>Human-controlled loan data verification</p></div><div className="user">{user.name}</div></header>{message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}{view==='dashboard'&&<Dashboard data={data} reload={()=>load('summary','/summary')}/>} {view==='upload'&&<Upload api={api} onDone={(x)=>{setMessage(`Imported ${x.rows_success} rows; ${x.exceptions_created||x.conflicts_created||0} exceptions created.`);setView('exceptions')}}/>}{view==='exceptions'&&<Exceptions api={api} user={user} setMessage={setMessage}/>} {view==='verified'&&<Verified api={api}/>} {view==='audit'&&<Audit api={api}/>}</main></div>
}
function Login({api,onLogin}){const [email,setEmail]=useState('operator@demo.local'),[password,setPassword]=useState('DemoPass123!'),[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{onLogin(await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})}))}catch(e){setError(e.message)}};return <div className="login"><section><span className="eyebrow">INTAIN CAMPUS FINTECH CHALLENGE</span><h1>Loan Data<br/><em>Verification Copilot</em></h1><p>Turn messy loan tapes into reviewable, AI-assisted, human-approved verified records.</p></section><form onSubmit={submit}><h2>Welcome back</h2><p>Use a seeded demo account to begin.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<small className="error">{error}</small>}<button className="primary">Sign in</button><small>Operator: upload · Reviewer: resolve · Consumer: verify/export</small></form></div>}
function Dashboard({data,reload}){const s=data.summary||{};return <><div className="toolbar"><button className="secondary" onClick={reload}>Refresh data</button></div><div className="cards">{[['Total loans',s.total_loans],['Exceptions',s.exceptions],['Open review',s.open_exceptions],['Verified',s.verified_loans],['Quality score',s.quality_score!==undefined?`${s.quality_score}%`:'—']].map(([a,b])=><article key={a}><span>{a}</span><strong>{b??'—'}</strong></article>)}</div><section className="panel"><h2>Trust pipeline</h2><div className="pipeline">Upload <b>→</b> Normalize <b>→</b> Validate <b>→</b> Review <b>→</b> Verify <b>→</b> Audit</div><p>Python rules detect issues. Groq explains and recommends. A reviewer makes every final decision.</p></section></>}
function Upload({api,onDone}){const [file,setFile]=useState(),[source,setSource]=useState('PRIMARY'),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();if(!file)return setError('Choose a CSV file first.');setBusy(true);try{const f=new FormData();f.append('file',file);const path=source==='PRIMARY'?'/uploads':`/uploads/secondary?source_type=${source}`;onDone(await api(path,{method:'POST',body:f}))}catch(e){setError(e.message)}finally{setBusy(false)}};return <section className="panel upload"><h2>Upload a source file</h2><p>Primary loan tape plus optional servicer and document-manifest sources are preserved as evidence.</p><form onSubmit={submit}><label>Source type<select value={source} onChange={e=>setSource(e.target.value)}><option value="PRIMARY">Loan tape</option><option value="SERVICER_UPDATE">Servicer update</option><option value="DOCUMENT_MANIFEST">Document manifest</option></select></label><label className="drop">Choose CSV<input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files[0])}/><span>{file?.name||'No file selected'}</span></label>{error&&<small className="error">{error}</small>}<button className="primary" disabled={busy}>{busy?'Importing…':'Start verification'}</button></form><p className="hint">Demo files are in the project’s <code>data</code> folder.</p></section>}
function Exceptions({api,user,setMessage}){const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState(''),[ai,setAi]=useState(null),[comment,setComment]=useState(''),[busy,setBusy]=useState(false);const load=async()=>{try{setRows(await api(`/exceptions${filter?`?severity=${filter}`:''}`))}catch(e){setMessage(e.message)}};useEffect(()=>{load()},[filter]);const act=async(path,body)=>{setBusy(true);try{const r=await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});setMessage('Action saved.');await load();return r}catch(e){setMessage(e.message)}finally{setBusy(false)}};return <div className="split"><section className="panel table"><div className="row"><h2>Exception queue</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All severities</option><option>HIGH</option><option>MEDIUM</option></select></div>{rows.map(r=><button className={`exception ${selected?._id===r._id?'selected':''}`} onClick={()=>{setSelected(r);setAi(null)}} key={r._id}><span><b>{r.loan_id||'Missing ID'}</b><small>{r.title}</small></span><i className={labels[r.severity]}>{r.severity}</i><em className={labels[r.status]}>{r.status}</em></button>)}{!rows.length&&<p>No exceptions yet. Upload the sample loan tape.</p>}</section><section className="panel detail">{selected?<><h2>{selected.title}</h2><p>{selected.description}</p><p><b>Loan:</b> {selected.loan_id} · <b>Fields:</b> {selected.affected_fields?.join(', ')}</p>{user.role!=='DATA_OPERATOR'&&<div className="actions"><button className="secondary" disabled={busy} onClick={()=>act(`/exceptions/${selected._id}/claim`)}>Claim</button><button className="primary" disabled={busy} onClick={async()=>setAi(await act(`/exceptions/${selected._id}/ai-review`))}>Ask AI</button></div>}{ai&&<div className="ai"><span>GROQ RECOMMENDATION · {ai.model}</span><p>{ai.response?.explanation}</p><b>Suggested: {ai.response?.suggested_field} → {String(ai.response?.suggested_value)}</b><small>Confidence: {ai.response?.confidence}</small></div>}{user.role!=='DATA_OPERATOR'&&<><div className="decision"><h3>Human decision</h3><button onClick={()=>act(`/exceptions/${selected._id}/decision`,{decision:'ACCEPT',field:ai?.response?.suggested_field,final_value:ai?.response?.suggested_value,comment:'Accepted after reviewer validation.'})}>Accept AI</button><button onClick={()=>act(`/exceptions/${selected._id}/decision`,{decision:'REJECT',comment:'Rejected after reviewer validation.'})}>Reject</button><button className="primary" onClick={()=>act(`/exceptions/${selected._id}/verify`)}>Create verified record</button></div><div className="comment"><input placeholder="Add reviewer note" value={comment} onChange={e=>setComment(e.target.value)}/><button onClick={()=>{act(`/exceptions/${selected._id}/comments`,{body:comment});setComment('')}}>Add</button></div></>}</>:<p>Select an exception to review.</p>}</section></div>}
function Verified({api}){const [rows,setRows]=useState([]);useEffect(()=>{api('/verified-records').then(setRows).catch(()=>setRows([]))},[]);return <section className="panel table"><div className="row"><h2>Verified records</h2><a className="secondary" href={`${API}/api/verified-records/export`} target="_blank">Export CSV</a></div>{rows.map(r=><article className="verified" key={r._id}><b>{r.loan_id}</b><span>Quality {r.quality_score}%</span><code>{r.record_hash}</code><small>{r.verification_timestamp}</small></article>)}{!rows.length&&<p>No verified records yet.</p>}</section>}
function Audit({api}){const [id,setId]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState('');const load=async e=>{e.preventDefault();try{setRows(await api(`/audit/${id}`));setError('')}catch(e){setError(e.message)}};return <section className="panel"><h2>Loan audit trail</h2><form className="inline" onSubmit={load}><input placeholder="Loan ID, e.g. LN-10002" value={id} onChange={e=>setId(e.target.value)}/><button className="primary">Open timeline</button></form>{error&&<p className="error">{error}</p>}<ol className="timeline">{rows.map(r=><li key={r._id}><b>{r.event_type}</b><span>{r.action_detail}</span><small>{r.timestamp}</small></li>)}</ol></section>}
createRoot(document.getElementById('root')).render(<App/>)
